FROM node:22-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app

COPY --from=builder /app/.output /app/.output

ENV STRAPI_URL=https://api.lippetennisunion.site
ENV NUXT_PUBLIC_API_URL=https://api.lippetennisunion.site

EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]